echo 关闭pcm-import系统开始...
kill -9 `cat /opt/app/pcm/pcm-import/main.pid`
echo 关闭pcm-import系统成功...
echo 拷贝编译jar包到应用目录 ...
rm -f /opt/app/pcm/pcm-import/*.jar
rm -f /opt/app/pcm/pcm-import/lib/*.jar
cp -f /root/.jenkins/jobs/pcm-import/workspace/target/pcm-import-0.0.3-SNAPSHOT.jar /opt/app/pcm/pcm-import/
cp -f /root/.jenkins/jobs/pcm-import/workspace/target/lib/*.jar /opt/app/pcm/pcm-import/lib/
echo 拷贝完成....
echo 开始运行服务...
#后台启动进程
BUILD_ID= java -jar /opt/app/pcm/pcm-import/pcm-import-0.0.3-SNAPSHOT.jar  start 8085 8075 >/opt/app/pcm/pcm-import/pcm-import.log 2>&1 &
echo $! > /opt/app/pcm/pcm-import/main.pid
echo 启动完毕.....
